plugins { id 'com.android.application' }

android {
    namespace 'ir.dastyar.eghsat'
    compileSdk 35

    defaultConfig {
        applicationId 'ir.dastyar.eghsat'
        minSdk 31
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}
